(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(tool-bar-mode 0)
(scroll-bar-mode 0)
;; (global-display-line-numbers-mode)
(setq auto-save-default nil)
(setq deft-auto-save-interval 0)
(global-visual-line-mode 1) ;; wrap word in a better way
(electric-pair-mode 1)
(setq inhibit-startup-screen t)
(setq system-time-locale "C")
(set-language-environment "UTF-8")
(setq make-backup-files nil)
(save-place-mode 1)
;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(set-face-attribute
'default nil
:font (font-spec :name "-outline-Consolas-bold-italic-normal-mono-*-*-*-*-c-*-iso10646-1"
      :weight 'normal
      :slant 'normal
      :size 14.0))
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font (frame-parameter nil 'font) charset (font-spec :name
                   "-outline-微软雅黑-normal-normal-normal-sans-*-*-*-*-p-*-iso10646-1"
                   :weight 'normal
                   :slant 'normal
                   :size 12.5)))
;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)
(custom-set-variables
;; custom-set-variables was added by Custom.
;; If you edit it by hand, you could mess it up, so be careful.
;; Your init file should contain only one such instance.
;; If there is more than one, they won't work right.
'(custom-safe-themes
   (quote
    ("0f0a4dca8bb029dc5139f447ff25bc3c18d31872c30a46d03c6bbc706ded3586" default)))
'(org-agenda-files (quote ("d:/RYB/work/schedule.org")))
'(org-export-backends (quote (ascii html icalendar latex md odt)))
'(org-log-into-drawer t)
'(package-selected-packages
   (quote
    (zenburn-theme indent-guide elisp-format openwith multiple-cursors iedit wgrep expand-region yasnippet-snippets use-package auctex counsel ivy deft markdown-mode company yasnippet cnfonts)))
'(safe-local-variable-values (quote ((org-refile-targets :level . 2)))))
(custom-set-faces
;; custom-set-faces was added by Custom.
;; If you edit it by hand, you could mess it up, so be careful.
;; Your init file should contain only one such instance.
;; If there is more than one, they won't work right.
)
;; zenburn-theme
(use-package zenburn-theme
  :ensure t
  :config
  (load-theme 'zenburn t))
;;  Openwith
(use-package
  openwith
  :config (progn (when
         (require 'openwith nil 'noerror)
       (setq openwith-associations (list
            ;; (list (openwith-make-extension-regexp
            ;;        '("mpg" "mpeg" "mp3" "mp4"
            ;;          "avi" "wmv" "wav" "mov" "flv"
            ;;          "ogm" "ogg" "mkv"))
            ;;       "audacious"
            ;;       '(file))
            ;; (list (openwith-make-extension-regexp
            ;;        '("xbm" "pbm" "pgm" "ppm" "pnm"
            ;;          "png" "bmp" "tif" "jpeg" "jpg"))
            ;;       "gpicview"
            ;;       '(file))
            (list (openwith-make-extension-regexp '("pdf"))
                  "SumatraPDF.exe" '(file))
            (list (openwith-make-extension-regexp '("doc"
                      "docx"))
                  "Word.exe" '(file))))
       (openwith-mode 1)))
  :ensure t)
;; deft
(use-package
  deft
  :ensure t
  :init (setq deft-extensions '("org"))
  (bind-key [f8] 'deft)
  (setq deft-directory "D:/RYB/work")
  (setq deft-recursive t)
  ;; (setq deft-use-filename-as-title t)
  (setq deft-use-filter-string-for-filename t)
  (setq deft-org-mode-title-prefix t)
  ;; (setq deft-auto-save-interval nil)
  (setq deft-file-naming-rules '((noslash . "-")
         (nospace . "-")
         (case-fn . downcase))))
;; Shortcuts for Markdown
(setq markdown-command "pandoc")
;; (defun end-of-line-and-indented-new-line ()
;;   (interactive)
;;   (end-of-line)
;;   (newline-and-indent))
;; (add-hook 'markdown-mode-hook
;;   (lambda ()
;;   (local-set-key (kbd "<C-return>") 'end-of-line-and-indented-new-line)
;;   (local-set-key (kbd "C-c C-i") 'markdown-insert-image)))
;; Open recent files
(recentf-mode 1)
(global-set-key (kbd "<f7>") 'recentf-open-files)
;; Org mode settings
;; (use-package auto-fill-mode
;;   :hook org-mode)
(use-package
  org
  :bind ("<f9>" . org-emphasize)
  ;; :hook (org-mode . org-indent-mode)
  :config
  (setq org-startup-truncated nil)
  (setq org-refile-targets '((nil :maxlevel . 3))))
;; find aspell and hunspell automatically
(cond
;; try hunspell at first
;; if hunspell does NOT exist, use aspell
((executable-find "hunspell")
  (setq ispell-program-name "hunspell")
  (setq ispell-local-dictionary "en_US")
  (setq ispell-hunspell-dictionary-alist
        ;; Please note the list `("-d" "en_US")` contains ACTUAL parameters passed to hunspell
        ;; You could use `("-d" "en_US,en_US-med")` to check with multiple dictionaries
        '(("en_US" "[[:alpha:]]" "[^[:alpha:]]" "[']" nil ("-d" "en_US") nil utf-8))))
((executable-find "aspell")
  (setq ispell-program-name "aspell")
  ;; Please note ispell-extra-args contains ACTUAL parameters passed to aspell
  (setq ispell-extra-args '("--sug-mode=ultra" "--lang=en_US"))))
;; ivy counsel swiper
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq enable-recursive-minibuffers t)
;; enable this if you want `swiper' to use it
;; (setq search-default-mode #'char-fold-to-regexp)
(global-set-key "\C-s" 'swiper)
;; (global-set-key (kbd "C-c C-r") 'ivy-resume)
(global-set-key (kbd "<f6>") 'ivy-resume)
(global-set-key (kbd "M-x") 'counsel-M-x)
(global-set-key (kbd "C-x C-f") 'counsel-find-file)
(global-set-key (kbd "<f1> f") 'counsel-describe-function)
(global-set-key (kbd "<f1> v") 'counsel-describe-variable)
(global-set-key (kbd "<f1> l") 'counsel-find-library)
(global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
;; (global-set-key (kbd "<f2> u") 'counsel-unicode-char)
;; (global-set-key (kbd "C-c g") 'counsel-git)
;; (global-set-key (kbd "C-c j") 'counsel-git-grep)
;; (global-set-key (kbd "C-c k") 'counsel-ag)
;; (global-set-key (kbd "C-c k") 'counsel-rg)
;; (global-set-key (kbd "C-x l") 'counsel-locate)
;; (global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
;; (define-key minibuffer-local-map (kbd "C-r") 'counsel-minibuffer-history)
(setq find-program "D:\\msys64\\usr\\bin\\find.exe")
(setq use-package-verbose t)
;; Highlight indent
(use-package indent-guide
  :ensure t)
;; Elisp auto format
(use-package elisp-format
  :ensure t)
;; yasnippet
(use-package
  yasnippet
  :ensure t
  :hook (org-mode . yas-minor-mode)
  :config
  ;; (use-package yasnippet-snippets)
  (bind-key "<f5>" 'yas-insert-snippet))
(use-package
  yasnippet-snippets
  :ensure t
  :after (yasnippet))
;; expand region
(use-package
  expand-region
  :ensure t
  :bind ("C-=" . 'er/expand-region))
;; Auctex
(use-package
  auctex
  :ensure t
  :hook (LaTeX-mode . LaTeX-math-mode)
  :config (setq TeX-auto-save t)
  (setq TeX-parse-self t))
;; (setq TeX-auto-save t)
;; (setq TeX-parse-self t)
;; (add-hook 'LaTeX-mode-hook 'LaTeX-math-mode)
;; company
(use-package
  company
  :ensure t
  :hook (after-init . global-company-mode)
  :config (setq company-dabbrev-downcase nil))
;; (use-package occur
;;   :bind ("M-n" . next-logical-line))
(put 'narrow-to-region 'disabled nil)
(use-package
  multiple-cursors
  :ensure t
  :init (setq mc/always-repeat-command t)
  (setq mc/always-run-for-all t))
;; Functions
(defun copy-line (arg)
  "Copy lines (as many as prefix argument) in the kill ring.
      Ease of use features:
      - Move to start of next line.
      - Appends the copy on sequential calls.
      - Use newline as last char even on the last line of the buffer.
      - If region is active, copy its lines."
  (interactive "p")
  (let ((beg (line-beginning-position))
  (end (line-end-position arg)))
    (when mark-active (if (> (point)
           (mark))
        (setq beg (save-excursion (goto-char (mark))
                (line-beginning-position)))
      (setq end (save-excursion (goto-char (mark))
              (line-end-position)))))
    (if (eq last-command 'copy-line)
  (kill-append
   (buffer-substring
    beg
    end)
   (< end beg))
      (kill-ring-save beg end)))
  (kill-append "\n" nil)
  (beginning-of-line (or (and arg
            (1+ arg))
       2))
  (if (and arg
     (not (= 1 arg)))
      (message "%d lines copied" arg)))
